<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
/**
 *
 * @package    auth_moowoodle
 * @author     DualCube <admin@dualcube.com>
 * @copyright  2023 DualCube Team(https://dualcube.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'MooWoodle Connect';
$string['moowoodle_plugin_message'] = 'It should be same with the wordpress plugin';
$string['key'] = 'SSO secret Key';
$string['wpsiteurl'] = 'Wordpress Site URL';
$string['wpsiteurl_message'] = 'For ex: http://your_wordpress_url/';
$string['wpsiteurl_help'] = 'The full URL of the WordPress site running the MooWoodle plugin, for example https://your-wordpress-site.com. Do not include a trailing slash.';
$string['key_help'] = 'A shared secret key used to encrypt single sign-on requests between Moodle and WordPress. The exact same key must be entered in the MooWoodle WordPress plugin settings.';
$string['timelimit'] = 'Set the time limit';
$string['timelimit_message'] = 'Define the duration in minutes for which the login link from the WordPress site remains active for Moodle site login.';
$string['timelimit_help'] = 'How long, in minutes, a single sign-on link generated by WordPress remains valid for logging in to this Moodle site.';
$string['moowoodle_settings'] = 'MooWoodle connect settings';
$string['privacy:metadata'] = 'The MooWoodle-based wordpress-authentication plugin does not store any personal data.';

// Settings page.
$string['settings_intro'] = 'Connect this site to the MooWoodle WordPress plugin. Use the setup wizard for a guided, step-by-step configuration.';
$string['runsetupwizard'] = 'Run setup wizard';
$string['redosetup'] = 'Restart wizard';
$string['gotosettings'] = 'Go to settings';
$string['managetokens'] = 'Manage web service tokens';

// Setup wizard: general.
$string['setupwizard'] = 'Setup wizard';
$string['step_requirements'] = 'Requirements';
$string['step_connection'] = 'Connection';
$string['step_webservice'] = 'Web service';
$string['step_finish'] = 'Finish';

// Setup wizard: requirements step.
$string['requirements_intro'] = 'Before connecting to WordPress, make sure your Moodle site meets the following requirements.';
$string['req_webservices'] = 'Web services are enabled';
$string['req_restprotocol'] = 'The REST protocol is enabled';
$string['req_extendedchars'] = 'Extended characters are allowed in usernames (recommended)';
$string['requirement_ok'] = 'Requirement met';
$string['requirement_missing'] = 'Requirement not met';
$string['fixthis'] = 'Fix this';

// Setup wizard: connection step.
$string['connection_intro'] = 'Enter the WordPress site URL and the shared secret key. The same key must be entered in the MooWoodle WordPress plugin settings.';
$string['testconnection'] = 'Test connection';
$string['saveandcontinue'] = 'Save and continue';
$string['testconnection_invalidurl'] = 'Please enter a valid WordPress site URL before testing the connection.';
$string['testconnection_unreachable'] = 'Could not reach {$a}. Check the URL and make sure the WordPress site is online.';
$string['testconnection_reachable'] = '{$a} is reachable. Full verification of the MooWoodle WordPress plugin still requires completing the setup on the WordPress side.';

// Setup wizard: web service step.
$string['webservice_intro'] = 'Create the Moodle web service and access token the MooWoodle WordPress plugin uses to sync users. The token is issued to your own admin account, so it must keep the required capabilities.';
$string['webservice_create'] = 'Create web service and token';
$string['webservice_recreate'] = 'Regenerate token';
$string['webservice_created_success'] = 'The web service and access token are ready.';
$string['webservice_created_fail'] = 'Could not create the web service: {$a}';
$string['webservice_token_label'] = 'Access token';
$string['webservice_heading'] = 'Web service';
$string['webservice_status_none'] = 'No web service has been created yet. Run the setup wizard to create one.';
$string['webservice_status_exists'] = 'Web service "{$a}" is set up.';

// Setup wizard: finish step.
$string['finish_intro'] = 'Setup complete. Copy the details below into the MooWoodle WordPress plugin settings.';
$string['finish_wpurl'] = 'WordPress site URL';
$string['finish_mdlurl'] = 'Moodle site URL';
$string['finish_token'] = 'Access token';
$string['finish_copy_note'] = 'Keep the secret key and access token private — anyone with them can sync user data between the two sites.';
