<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
/**
 *
 * @package    auth_moowoodle
 * @author     DualCube <admin@dualcube.com>
 * @copyright  2023 DualCube Team(https://dualcube.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'MooWoodle Connect';
$string['moowoodle_plugin_message'] = 'It should be same with the wordpress plugin';
$string['key'] = 'SSO secret Key';
$string['wpsiteurl'] = 'Wordpress Site URL';
$string['wpsiteurl_message'] = 'For ex: http://your_wordpress_url/';
$string['wpsiteurl_help'] = 'The full URL of the WordPress site running the MooWoodle plugin, for example https://your-wordpress-site.com. Do not include a trailing slash.';
$string['key_help'] = 'A shared secret key used to encrypt single sign-on requests between Moodle and WordPress. The exact same key must be entered in the MooWoodle WordPress plugin settings.';
$string['timelimit'] = 'Set the time limit';
$string['timelimit_message'] = 'Define the duration in minutes for which the login link from the WordPress site remains active for Moodle site login.';
$string['timelimit_help'] = 'How long, in minutes, a single sign-on link generated by WordPress remains valid for logging in to this Moodle site.';
$string['moowoodle_settings'] = 'MooWoodle connect settings';
$string['privacy:metadata'] = 'The MooWoodle-based wordpress-authentication plugin does not store any personal data.';

// Settings page.
$string['settings_intro'] = 'Connect this site to the MooWoodle WordPress plugin. Use the setup wizard for a guided, step-by-step configuration.';
$string['runsetupwizard'] = 'Run setup wizard';
$string['redosetup'] = 'Restart wizard';
$string['gotosettings'] = 'Go to settings';
$string['managetokens'] = 'Manage web service tokens';

// Setup wizard: general.
$string['setupwizard'] = 'Setup wizard';
$string['step_requirements'] = 'General';
$string['step_connection'] = 'Wordpress Site';
$string['step_webservice'] = 'Web Service';
$string['step_synchronization'] = 'Synchronization';
$string['step_summary'] = 'Summary';
$string['save'] = 'Save';
$string['settingssaved'] = 'Settings saved.';
$string['recommendedyes'] = 'Recommended: yes';
$string['recommendedno'] = 'Recommended: no';
$string['copy'] = 'Copy';

// Setup wizard: General step.
$string['requirements_intro'] = 'Before connecting to WordPress, make sure your Moodle site meets the following requirements.';
$string['req_webservices'] = 'Enable web services';
$string['req_webservices_desc'] = 'Web services must be enabled so the MooWoodle WordPress plugin can call this site over the API.';
$string['req_restprotocol'] = 'Enable REST protocol';
$string['req_restprotocol_desc'] = 'The MooWoodle WordPress plugin communicates using the REST web service protocol.';
$string['req_passwordpolicy'] = 'Password policy';
$string['req_passwordpolicy_desc'] = 'If enabled, user passwords will be checked against the password policy configured under Site administration > Security. Leaving this off avoids conflicts when WordPress supplies its own passwords.';
$string['req_extendedchars'] = 'Allow extended characters in usernames';
$string['req_extendedchars_desc'] = 'Allows usernames created from WordPress to include characters beyond the Moodle default (alphanumeric, underscore, hyphen, period, at symbol).';
$string['requirement_ok'] = 'Requirement met';
$string['requirement_missing'] = 'Requirement not met';
$string['fixthis'] = 'Fix this';

// Setup wizard: connection step.
$string['connection_intro'] = 'Enter the WordPress site URL and the shared secret key. The same key must be entered in the MooWoodle WordPress plugin settings.';
$string['testconnection'] = 'Test connection';
$string['saveandcontinue'] = 'Save and continue';
$string['testconnection_invalidurl'] = 'Please enter a valid WordPress site URL before testing the connection.';
$string['testconnection_unreachable'] = 'Could not reach {$a}. Check the URL and make sure the WordPress site is online.';
$string['testconnection_reachable'] = '{$a} is reachable. Full verification of the MooWoodle WordPress plugin still requires completing the setup on the WordPress side.';

// Setup wizard: Web Service step.
$string['webservice_intro'] = 'Choose which web service and user the MooWoodle WordPress plugin should authenticate as, then copy the site URL and token into the WordPress plugin settings.';
$string['webservice_create'] = 'Create web service and token';
$string['webservice_recreate'] = 'Regenerate token';
$string['webservice_created_success'] = 'The web service and access token are ready.';
$string['webservice_created_fail'] = 'Could not create the web service: {$a}';
$string['webservice_token_label'] = 'Token';
$string['webservice_heading'] = 'Web service';
$string['webservice_status_none'] = 'No web service has been created yet. Run the setup wizard to create one.';
$string['webservice_status_exists'] = 'Web service "{$a}" is set up.';
$string['webservice_selectservice'] = 'Select web service';
$string['webservice_selectplaceholder'] = 'Select web service';
$string['webservice_createnew'] = '- Create new web service -';
$string['webservice_newservicename'] = 'Name for the Web Service';
$string['webservice_selectuser'] = 'Select user';
$string['webservice_selecttoken'] = 'Select token';
$string['webservice_langcode'] = 'Language code';
$string['webservice_siteurl'] = 'Site URL';
$string['webservice_update'] = 'Update web service';
$string['reload'] = 'Reload';
$string['webservice_nouser'] = 'No eligible user found. The selected user needs the "moodle/webservice:createtoken" capability.';

// Setup wizard: Web Service step, additional function grants.
$string['synchronization_intro'] = 'Choose which additional web service functions the MooWoodle WordPress plugin is allowed to call. The functions required by this plugin are always enabled. Only enable functions the WordPress site actually needs — each one grants real access to Moodle data. Checking a box grants that function immediately; unchecking it here does not revoke access already granted — remove a function from Site administration > Server > Web services > External services if needed.';

// Setup wizard: Summary step.
$string['summary_intro'] = 'Review the configuration below, then copy the connection details into the MooWoodle WordPress plugin settings.';
$string['summary_general_heading'] = 'General settings summary';
$string['summary_connection_heading'] = 'Connection settings summary';
$string['summary_webservicefunctions'] = 'Web service function';
$string['summary_capability'] = 'Capability';
$string['summary_moodleurl'] = 'Moodle URL';
$string['summary_webservicename'] = 'Web service name';
$string['summary_wordpressurl'] = 'Wordpress URL';
$string['summary_connectionstatus'] = 'Connection status';
$string['summary_langcode'] = 'Language code';
$string['summary_notset'] = 'Not set up yet';
$string['summary_copy_note'] = 'Keep the secret key and access token private — anyone with them can sync user data between the two sites.';
$string['enabled'] = 'Enabled';
$string['disabled'] = 'Disabled';
$string['connectionok'] = 'Reachable';
$string['checkmoredetails'] = 'Check the Wordpress Site step for details.';
